# Generated by Django 2.2.10 on 2020-03-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20200301_0026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
