# Generated by Django 2.2.10 on 2020-04-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_delete_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['id'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['id'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
